# Generated by Django 3.2.8 on 2021-12-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='power',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
