# Generated by Django 3.2.8 on 2021-12-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_doc_eva_recollect_evaluate_feed_back_group_grade_group_record_student_task_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='group_id',
            field=models.IntegerField(verbose_name='小组编号'),
        ),
        migrations.AlterField(
            model_name='feed_back',
            name='group_id',
            field=models.IntegerField(verbose_name='小组编号'),
        ),
        migrations.AlterField(
            model_name='group_grade',
            name='group_id',
            field=models.IntegerField(verbose_name='小组编号'),
        ),
        migrations.AlterField(
            model_name='group_record',
            name='group_id',
            field=models.IntegerField(verbose_name='小组编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_id',
            field=models.IntegerField(verbose_name='小组编号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group_id',
            field=models.IntegerField(verbose_name='小组编号'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_id',
            field=models.IntegerField(verbose_name='小组编号'),
        ),
    ]
