# Generated by Django 3.2.8 on 2021-12-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20211221_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='evaluate_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='评价编号'),
        ),
    ]
