# Generated by Django 3.2.8 on 2022-01-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_alter_evaluate_evaluate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='num',
            field=models.CharField(max_length=11, verbose_name='学生学号'),
        ),
    ]
