# Generated by Django 3.2.8 on 2022-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_alter_task_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default=0, max_length=3, verbose_name='任务类型'),
            preserve_default=False,
        ),
    ]
