# Generated by Django 3.2.8 on 2022-03-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0011_learn_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn_obj',
            name='obj_topic',
            field=models.CharField(default=0, max_length=255, verbose_name='教学主题'),
            preserve_default=False,
        ),
    ]
