# Generated by Django 3.2.8 on 2022-03-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0012_learn_obj_obj_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='init_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=32, verbose_name='文件名称')),
                ('file_path', models.CharField(max_length=255, verbose_name='文件路径')),
                ('file_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_type', models.CharField(max_length=6, verbose_name='文件类型')),
            ],
        ),
    ]
