# Generated by Django 3.2.8 on 2022-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0013_init_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_id',
            field=models.CharField(default=0, max_length=16, unique=True, verbose_name='子任务的上一级任务'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learn_obj',
            name='obj_content',
            field=models.CharField(max_length=255, verbose_name='教学目标'),
        ),
    ]
