# Generated by Django 3.2.8 on 2022-03-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0014_auto_20220321_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_id',
            field=models.CharField(max_length=16, verbose_name='子任务的上一级任务'),
        ),
    ]
