# Generated by Django 3.2.8 on 2022-04-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0026_auto_20220402_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='submit_time',
        ),
    ]
