# Generated by Django 3.2.8 on 2022-04-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0027_remove_doc_submit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='submit_type',
        ),
    ]
