# Generated by Django 3.2.8 on 2022-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0028_remove_doc_submit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='submit_type',
            field=models.CharField(default=1, max_length=10, verbose_name='上传类型'),
            preserve_default=False,
        ),
    ]
