# Generated by Django 3.2.8 on 2022-04-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0029_doc_submit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='file_type',
            field=models.CharField(default=1, max_length=6, verbose_name='文件类型'),
            preserve_default=False,
        ),
    ]
