# Generated by Django 3.2.8 on 2022-04-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0030_doc_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='num',
            field=models.CharField(max_length=11, verbose_name='学生学号'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='task_id',
            field=models.CharField(max_length=16, verbose_name='任务编号'),
        ),
    ]
