# Generated by Django 3.2.8 on 2022-04-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0031_auto_20220402_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file_content',
            field=models.TextField(verbose_name='文件路径/文本'),
        ),
    ]
