# Generated by Django 3.2.8 on 2022-04-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0032_alter_doc_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overtime_days',
            field=models.IntegerField(default=0, verbose_name='延迟天数'),
        ),
    ]
