# Generated by Django 3.2.8 on 2022-04-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0033_task_overtime_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_num', models.CharField(max_length=11, verbose_name='学生学号')),
                ('receive_num', models.CharField(max_length=11, verbose_name='学生学号')),
                ('notice_title', models.CharField(max_length=255, verbose_name='通知标题')),
                ('notice_content', models.TextField(verbose_name='通知信息')),
                ('notice_type', models.CharField(max_length=10, verbose_name='通知类型')),
                ('notice_time', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
            ],
        ),
    ]
