# Generated by Django 3.2.8 on 2022-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0034_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_back',
            name='feedback_title',
            field=models.CharField(default='title', max_length=32, verbose_name='反馈标题'),
        ),
        migrations.AddField(
            model_name='feed_back',
            name='num',
            field=models.CharField(default='stu_num', max_length=11, verbose_name='学生学号'),
        ),
        migrations.AlterField(
            model_name='feed_back',
            name='feedback_content',
            field=models.TextField(verbose_name='反馈内容'),
        ),
    ]
