# Generated by Django 3.2.8 on 2022-04-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0035_auto_20220405_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_back',
            name='feedback_file',
            field=models.CharField(default='nofile', max_length=255, verbose_name='反馈文件地址'),
        ),
    ]
