# Generated by Django 3.2.8 on 2022-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0036_feed_back_feedback_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_back',
            name='feedback_file',
            field=models.TextField(default='nofile', verbose_name='反馈文件地址'),
        ),
    ]
