# Generated by Django 3.2.8 on 2022-04-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0037_alter_feed_back_feedback_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_id', models.IntegerField(verbose_name='反馈编号')),
                ('file_path', models.CharField(default='title', max_length=32, verbose_name='反馈标题')),
            ],
        ),
        migrations.AlterField(
            model_name='feed_back',
            name='feedback_file',
            field=models.IntegerField(default=0, verbose_name='文件个数'),
        ),
    ]
