# Generated by Django 3.2.8 on 2022-04-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0038_auto_20220405_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_back',
            name='feedback_id',
            field=models.CharField(default='0000', max_length=16, verbose_name='反馈表编号'),
        ),
    ]
