# Generated by Django 3.2.8 on 2022-04-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0039_feed_back_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackfile',
            name='file_path',
            field=models.CharField(default='title', max_length=255, verbose_name='反馈标题'),
        ),
    ]
