# Generated by Django 3.2.8 on 2022-04-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0040_alter_feedbackfile_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(verbose_name='小组编号')),
                ('send_num', models.CharField(max_length=11, verbose_name='学生学号')),
                ('send_content', models.TextField(verbose_name='发送内容')),
                ('send_type', models.TextField(verbose_name='发送类型')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_send', models.BooleanField(verbose_name='是否是自己发送')),
            ],
        ),
    ]
