# Generated by Django 3.2.8 on 2022-04-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0041_groupchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='is_send',
        ),
    ]
