# Generated by Django 3.2.8 on 2022-04-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0042_remove_groupchat_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='struct_type',
            field=models.IntegerField(default=0, verbose_name='结构类型'),
        ),
    ]
