# Generated by Django 3.2.8 on 2022-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0043_evaluate_struct_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eva_recollect',
            name='beeva_name',
        ),
        migrations.RemoveField(
            model_name='eva_recollect',
            name='eva_score',
        ),
        migrations.RemoveField(
            model_name='eva_recollect',
            name='valuer_name',
        ),
        migrations.AddField(
            model_name='eva_recollect',
            name='beeva_num',
            field=models.CharField(default='无', max_length=32, verbose_name='被评价者学号/被评价小组编号'),
        ),
        migrations.AddField(
            model_name='eva_recollect',
            name='eva_content',
            field=models.CharField(default='无', max_length=255, verbose_name='评价内容(根据问卷结构类型的不同而不同)(分值/时长/文本)'),
        ),
        migrations.AddField(
            model_name='eva_recollect',
            name='eva_type',
            field=models.CharField(default='尚未指定', max_length=32, verbose_name='评价类型'),
        ),
        migrations.AddField(
            model_name='eva_recollect',
            name='from_type',
            field=models.CharField(default='0', max_length=6, verbose_name='问卷结构类型'),
        ),
        migrations.AddField(
            model_name='eva_recollect',
            name='group_id',
            field=models.IntegerField(default=0, verbose_name='小组编号'),
        ),
        migrations.AddField(
            model_name='eva_recollect',
            name='valuer_num',
            field=models.CharField(default='00000000', max_length=32, verbose_name='评价者学号'),
        ),
        migrations.AlterField(
            model_name='eva_recollect',
            name='act_name',
            field=models.CharField(max_length=64, verbose_name='活动名称(小组学习名称)'),
        ),
    ]
