# Generated by Django 3.2.8 on 2022-04-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0044_auto_20220412_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eva_recollect',
            old_name='from_type',
            new_name='form_type',
        ),
    ]
