# Generated by Django 3.2.8 on 2022-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0045_rename_from_type_eva_recollect_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eva_recollect',
            name='pj_id',
            field=models.CharField(default='0', max_length=16, verbose_name='评价编号'),
        ),
    ]
