# Generated by Django 3.2.8 on 2022-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0046_eva_recollect_pj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eva_recollect',
            name='pj_id',
            field=models.IntegerField(default='0', verbose_name='评价编号'),
        ),
    ]
