# Generated by Django 3.2.8 on 2022-04-25 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0047_alter_eva_recollect_pj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
