# Generated by Django 3.2.8 on 2022-04-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0049_alter_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='xxxxxxxx', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='xxxxxxxx', max_length=13),
        ),
    ]
