# Generated by Django 3.2.8 on 2022-06-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0050_auto_20220429_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='group_grade',
        ),
        migrations.DeleteModel(
            name='group_record',
        ),
    ]
