# Generated by Django 3.2.8 on 2022-06-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0051_auto_20220603_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
